//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomaticBelling.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/10/2014 09:40:00")]
        public global::System.DateTime nowtime {
            get {
                return ((global::System.DateTime)(this["nowtime"]));
            }
            set {
                this["nowtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool timerstat {
            get {
                return ((bool)(this["timerstat"]));
            }
            set {
                this["timerstat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>09:25:00 AM</string>
  <string>09:30:00 AM</string>
  <string>09:30:22 AM</string>
  <string>10:30:00 AM</string>
  <string>11:30:00 AM</string>
  <string>11:35:00 AM</string>
  <string>12:35:00 PM</string>
  <string>01:15:00 PM</string>
  <string>02:00:00 PM</string>
  <string>03:00:00 PM</string>
  <string>04:00:00 PM</string>
  <string>04:00:17 PM</string>
  <string>04:01:10 PM</string>
  <string>04:04:00 PM</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection friday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["friday"]));
            }
            set {
                this["friday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>09:25:00 AM</string>
  <string>09:30:00 AM</string>
  <string>09:30:22 AM</string>
  <string>10:30:00 AM</string>
  <string>11:30:00 AM</string>
  <string>11:35:00 AM</string>
  <string>12:35:00 PM</string>
  <string>01:15:00 PM</string>
  <string>01:30:00 PM</string>
  <string>02:30:00 PM</string>
  <string>03:30:00 PM</string>
  <string>03:30:13 PM</string>
  <string>03:31:05 PM</string>
  <string>03:34:00 PM</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection allday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["allday"]));
            }
            set {
                this["allday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:30:22 AM")]
        public string prayerf {
            get {
                return ((string)(this["prayerf"]));
            }
            set {
                this["prayerf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:30:22 AM")]
        public string prayer {
            get {
                return ((string)(this["prayer"]));
            }
            set {
                this["prayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03:30:13 PM")]
        public string nationalanthem {
            get {
                return ((string)(this["nationalanthem"]));
            }
            set {
                this["nationalanthem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04:00:17 PM")]
        public string nationalanthemf {
            get {
                return ((string)(this["nationalanthemf"]));
            }
            set {
                this["nationalanthemf"] = value;
            }
        }
    }
}
